CREATE DATABASE IF NOT EXISTS toolloot
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE toolloot;

CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  name VARCHAR(24) NOT NULL,
  email VARCHAR(191) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  cash BIGINT UNSIGNED NOT NULL DEFAULT 0,
  ore BIGINT UNSIGNED NOT NULL DEFAULT 0,
  zone INT UNSIGNED NOT NULL DEFAULT 1,
  bulldozer_level INT UNSIGNED NOT NULL DEFAULT 1,
  tool_level INT UNSIGNED NOT NULL DEFAULT 1,
  workers INT UNSIGNED NOT NULL DEFAULT 0,
  score BIGINT UNSIGNED NOT NULL DEFAULT 0,
  wins INT UNSIGNED NOT NULL DEFAULT 0,
  kills INT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_score ON users(score);
