import express from "express";
import http from "node:http";
import cors from "cors";
import {Server} from "socket.io";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import mariadb from "mariadb";
import nodemailer from "nodemailer";
import "dotenv/config";
import crypto from "node:crypto";
const app=express(),server=http.createServer(app),io=new Server(server,{cors:{origin:"*"}});app.use(cors());app.use(express.json());
const pool=mariadb.createPool({host:process.env.DB_HOST||"127.0.0.1",port:Number(process.env.DB_PORT||3306),user:process.env.DB_USER||"root",password:process.env.DB_PASSWORD||"",database:process.env.DB_NAME||"toolloot",connectionLimit:5});
const JWT_SECRET=process.env.JWT_SECRET||"change-this-secret",clean=v=>String(v||"").trim(),phone=v=>String(v||"").replace(/\D/g,"").replace(/^0+/,""),hash=c=>crypto.createHash("sha256").update(String(c)).digest("hex");
const mailer=process.env.SMTP_HOST?nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:String(process.env.SMTP_SECURE)==="true",auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}}):null;
const auth=(req,res,next)=>{try{req.user=jwt.verify((req.headers.authorization||"").replace(/^Bearer\s+/i,""),JWT_SECRET);next()}catch{res.status(401).json({error:"Unauthorized"})}};
async function setup(){await pool.query("CREATE TABLE IF NOT EXISTS email_otps (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,email VARCHAR(255) NOT NULL,code_hash VARCHAR(255) NOT NULL,expires_at DATETIME NOT NULL,attempts INT NOT NULL DEFAULT 0,verified_at DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX(email,created_at))");
for(const q of ["ALTER TABLE users ADD COLUMN username VARCHAR(60) NULL UNIQUE","ALTER TABLE users ADD COLUMN phone VARCHAR(20) NULL UNIQUE"]){try{await pool.query(q)}catch(e){if(!String(e.code).includes("DUPLICATE")&&!String(e.code).includes("EXISTS")){}}}}
async function sendOtp(email,code){if(!mailer){if(process.env.NODE_ENV!=="production")return code;throw Error("Email SMTP is not configured")}await mailer.sendMail({from:process.env.SMTP_FROM||process.env.SMTP_USER,to:email,subject:"ToollooT verification code",text:"Your ToollooT verification code is "+code+". It expires in 5 minutes.",html:"<h2>ToollooT</h2><p>Your verification code is <b style='font-size:28px'>"+code+"</b></p><p>This code expires in 5 minutes.</p>"});return null}
app.get("/api/health",async(_,res)=>{try{await setup();res.json({ok:true})}catch{res.status(503).json({ok:false})}});
app.post("/api/request-otp",async(req,res)=>{const email=clean(req.body?.email).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return res.status(400).json({error:"Enter a valid email address"});try{await setup();if((await pool.query("SELECT id FROM users WHERE email=? LIMIT 1",[email])).length)return res.status(409).json({error:"Email already registered"});const recent=await pool.query("SELECT id FROM email_otps WHERE email=? AND created_at>=DATE_SUB(NOW(),INTERVAL 60 SECOND) LIMIT 1",[email]);if(recent.length)return res.status(429).json({error:"Please wait 60 seconds before requesting another OTP"});const code=String(crypto.randomInt(100000,1000000));await pool.query("INSERT INTO email_otps(email,code_hash,expires_at) VALUES(?,?,DATE_ADD(NOW(),INTERVAL 5 MINUTE))",[email,hash(code)]);const demo=await sendOtp(email,code);res.json({ok:true,expiresIn:300,demoOtp:demo||undefined})}catch(e){res.status(500).json({error:e.message==="Email SMTP is not configured"?"Email service is not configured yet": "Could not send OTP"})}});
app.post("/api/verify-otp",async(req,res)=>{const email=clean(req.body?.email).toLowerCase(),code=clean(req.body?.code);try{const r=await pool.query("SELECT id,code_hash,expires_at,attempts FROM email_otps WHERE email=? AND verified_at IS NULL ORDER BY id DESC LIMIT 1",[email]);if(!r.length||new Date(r[0].expires_at)<new Date())return res.status(400).json({error:"OTP expired. Request a new code."});if(r[0].attempts>=5)return res.status(429).json({error:"Too many attempts. Request a new OTP."});if(hash(code)!==r[0].code_hash){await pool.query("UPDATE email_otps SET attempts=attempts+1 WHERE id=?",[r[0].id]);return res.status(400).json({error:"Incorrect OTP"})}await pool.query("UPDATE email_otps SET verified_at=NOW() WHERE id=?",[r[0].id]);res.json({ok:true})}catch{res.status(500).json({error:"OTP verification failed"})}});
app.post("/api/register",async(req,res)=>{const name=clean(req.body?.name),username=clean(req.body?.username).toLowerCase(),p=phone(req.body?.phone),email=clean(req.body?.email).toLowerCase(),password=String(req.body?.password||"");if(!name||!p||p.length<10||!email||!username||!/^[a-z0-9_]{3,30}$/.test(username)||password.length<6)return res.status(400).json({error:"Enter all required details correctly"});try{const v=await pool.query("SELECT id FROM email_otps WHERE email=? AND verified_at IS NOT NULL AND verified_at>=DATE_SUB(NOW(),INTERVAL 10 MINUTE) ORDER BY id DESC LIMIT 1",[email]);if(!v.length)return res.status(403).json({error:"Verify your email with OTP first"});const r=await pool.query("INSERT INTO users(name,username,phone,email,password_hash,status,last_seen) VALUES(?,?,?,?,?,?,NOW())",[name,username,p,email,await bcrypt.hash(password,12),"Available"]);const user={id:Number(r.insertId),name,username,phone:p,email};res.json({token:jwt.sign({userId:user.id},JWT_SECRET,{expiresIn:"7d"}),user})}catch(e){if(e?.code==="ER_DUP_ENTRY")return res.status(409).json({error:"Username, email or mobile number already registered"});res.status(500).json({error:"Registration failed"})}});
app.post("/api/login",async(req,res)=>{const id=clean(req.body?.login).toLowerCase(),password=String(req.body?.password||"");try{const r=await pool.query("SELECT id,name,username,phone,email,password_hash FROM users WHERE email=? OR username=? OR phone=? LIMIT 1",[id,id,phone(id)]);if(!r.length||!(await bcrypt.compare(password,r[0].password_hash)))return res.status(401).json({error:"Invalid login details or password"});await pool.query("UPDATE users SET last_seen=NOW(),status='online' WHERE id=?",[r[0].id]);const user={id:Number(r[0].id),name:r[0].name,username:r[0].username,phone:r[0].phone,email:r[0].email};res.json({token:jwt.sign({userId:user.id},JWT_SECRET,{expiresIn:"7d"}),user})}catch{res.status(500).json({error:"Login failed"})}});
app.get("/api/me",auth,async(req,res)=>{const r=await pool.query("SELECT id,name,username,phone,email,avatar_url,status,last_seen,created_at FROM users WHERE id=?",[req.user.userId]);if(!r.length)return res.status(404).json({error:"User not found"});res.json({user:r[0]})});
async function memberOf(cid,uid){return (await pool.query("SELECT 1 FROM conversation_members WHERE conversation_id=? AND user_id=? LIMIT 1",[cid,uid])).length>0}
app.get("/api/users/search",auth,async(req,res)=>{const q=clean(req.query.q);if(q.length<2)return res.json({users:[]});const r=await pool.query("SELECT id,name,username,phone,email,avatar_url,status,last_seen FROM users WHERE id<>? AND (username LIKE ? OR phone LIKE ? OR name LIKE ?) ORDER BY name LIMIT 30",[req.user.userId,"%"+q+"%","%"+phone(q)+"%","%"+q+"%"]);res.json({users:r.map(u=>({...u,id:Number(u.id)}))})});
app.post("/api/conversations/direct",auth,async(req,res)=>{const tid=Number(req.body?.userId);if(!tid||tid===Number(req.user.userId))return res.status(400).json({error:"Choose another user"});const target=await pool.query("SELECT id,name,username,phone,avatar_url,status,last_seen FROM users WHERE id=?",[tid]);if(!target.length)return res.status(404).json({error:"User not found"});const ex=await pool.query("SELECT c.id FROM conversations c JOIN conversation_members cm ON cm.conversation_id=c.id WHERE c.type='direct' AND cm.user_id IN (?,?) GROUP BY c.id HAVING COUNT(DISTINCT cm.user_id)=2 AND (SELECT COUNT(*) FROM conversation_members x WHERE x.conversation_id=c.id)=2 LIMIT 1",[req.user.userId,tid]);let cid=ex.length?Number(ex[0].id):0;if(!cid){const c=await pool.getConnection();try{await c.beginTransaction();const x=await c.query("INSERT INTO conversations(type) VALUES('direct')");cid=Number(x.insertId);await c.query("INSERT INTO conversation_members(conversation_id,user_id) VALUES(?,?),(?,?)",[cid,req.user.userId,cid,tid]);await c.commit()}catch(e){await c.rollback();throw e}finally{c.release()}}res.json({conversation:{id:cid,type:"direct"},user:{...target[0],id:Number(target[0].id)}})});
app.get("/api/conversations",auth,async(req,res)=>{const r=await pool.query("SELECT c.id,c.type,c.name,u.id member_id,u.name member_name,u.username member_username,u.phone member_phone,u.status member_status,lm.text last_text,lm.created_at last_created FROM conversations c JOIN conversation_members mine ON mine.conversation_id=c.id AND mine.user_id=? LEFT JOIN conversation_members other ON other.conversation_id=c.id AND other.user_id<>? LEFT JOIN users u ON u.id=other.user_id LEFT JOIN messages lm ON lm.id=(SELECT MAX(x.id) FROM messages x WHERE x.conversation_id=c.id) ORDER BY COALESCE(lm.created_at,c.created_at) DESC",[req.user.userId,req.user.userId]);res.json({conversations:r.map(x=>({id:Number(x.id),group:x.type==="group",name:x.type==="group"?(x.name||"Group"):(x.member_name||"Unknown"),initial:(x.member_name||"G")[0].toUpperCase(),online:x.member_status==="online",last:x.last_text||"No messages yet",time:x.last_created?new Date(x.last_created).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}):"Now",unread:0,messages:[],userId:x.member_id?Number(x.member_id):null,phone:x.member_phone||""}))})});
app.get("/api/conversations/:id/messages",auth,async(req,res)=>{const id=Number(req.params.id);if(!id||!(await memberOf(id,req.user.userId)))return res.status(403).json({error:"Conversation access denied"});const r=await pool.query("SELECT id,conversation_id,sender_id,text,created_at FROM messages WHERE conversation_id=? ORDER BY created_at,id",[id]);res.json({messages:r.map(m=>({id:Number(m.id),conversationId:Number(m.conversation_id),senderId:Number(m.sender_id),text:m.text||"",time:new Date(m.created_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}),me:Number(m.sender_id)===Number(req.user.userId)}))})});
io.use((s,n)=>{try{s.user=jwt.verify(s.handshake.auth?.token,JWT_SECRET);n()}catch{n(new Error("Unauthorized"))}});io.on("connection",s=>{pool.query("UPDATE users SET status='online',last_seen=NOW() WHERE id=?",[s.user.userId]).catch(()=>{});s.on("conversation:join",async id=>{if(await memberOf(Number(id),s.user.userId))s.join(String(id))});s.on("typing",async d=>{const id=Number(d?.conversationId);if(id&&await memberOf(id,s.user.userId))s.to(String(id)).emit("typing",{conversationId:id,userId:s.user.userId,isTyping:!!d.isTyping})});s.on("message:send",async d=>{const id=Number(d?.conversationId),body=clean(d?.text);if(!id||!body||body.length>10000||!(await memberOf(id,s.user.userId)))return;try{const r=await pool.query("INSERT INTO messages(conversation_id,sender_id,text) VALUES(?,?,?)",[id,s.user.userId,body]);io.to(String(id)).emit("message:new",{id:Number(r.insertId),conversationId:id,senderId:Number(s.user.userId),text:body,createdAt:new Date().toISOString()})}catch{}});s.on("disconnect",()=>pool.query("UPDATE users SET status='offline',last_seen=NOW() WHERE id=?",[s.user.userId]).catch(()=>{}))});
setup().catch(e=>console.error("DB setup:",e.message));server.listen(Number(process.env.PORT||5186),()=>console.log("ToollooT Chat server listening"));