import React,{useEffect,useState}from"react";
import Swal from"sweetalert2";
import{LogIn,UserPlus,LogOut,Users,Mail,Lock,User,ShieldCheck,Cloud,BarChart3}from"lucide-react";
import"./account.css";
const API=import.meta.env.VITE_TOOLLOOT_API||"";
const KEY="toolloot:account";
const save=v=>localStorage.setItem(KEY,JSON.stringify(v));
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||"null")}catch{return null}};
async function request(path,body){const r=await fetch(API+path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Request failed");return d}
export function AccountPage(){
 const [account,setAccount]=useState(load),[mode,setMode]=useState("login"),[name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[loading,setLoading]=useState(false);
 const submit=async e=>{e.preventDefault();setLoading(true);try{
   let d=await request(mode==="login"?"/api/auth/login":"/api/auth/register",{name,email,password});
   const a={...d.user,token:d.token,server:true};save(a);setAccount(a);Swal.fire({icon:"success",title:mode==="login"?"Welcome back":"Account created",toast:true,position:"bottom-end",showConfirmButton:false,timer:1800});
 }catch(err){if(API)Swal.fire({icon:"error",title:"Server unavailable",text:err.message});else{const a={id:crypto.randomUUID(),name:name||"ToollooT User",email,mode:"local",token:null};save(a);setAccount(a)}}finally{setLoading(false)}};
 if(account)return <div className="accountPage"><div className="accountCard accountWelcome"><div className="accountMark">T•T</div><ShieldCheck size={28}/><h1>You're in, {account.name}</h1><p>{account.email}</p><div className="accountStats"><div><Users/><b>Personal</b><span>Workspace</span></div><div><ShieldCheck/><b>{account.server?"Cloud-ready":"Local-first"}</b><span>Account mode</span></div></div><div style={{display:"flex",gap:"8px",flexWrap:"wrap",justifyContent:"center"}}><a className="accountPrimary" href="../workspace"><Cloud size={16}/>Workspace</a>{account.isPlatformOwner&&<a className="accountPrimary" href="../owner-analytics"><BarChart3 size={16}/>Owner Analytics</a>}<button className="accountPrimary" onClick={async()=>{try{if(account.token)await request("/api/auth/logout",{});}catch{}localStorage.removeItem(KEY);setAccount(null)}}><LogOut size={16}/>Log out</button></div></div></div>;
 return <div className="accountPage"><div className="accountCard"><div className="accountMark">T•T</div><h1>{mode==="login"?"Welcome back":"Create your free account"}</h1><p>One free identity for chats, memory, teams and future ToollooT services.</p><form onSubmit={submit}>{mode==="register"&&<label><User/>Name<input value={name} onChange={e=>setName(e.target.value)} required/></label>}<label><Mail/>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label><Lock/>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength="6" required/></label><button className="accountPrimary" disabled={loading}>{mode==="login"?<LogIn/>:<UserPlus/>}{loading?"Please wait…":mode==="login"?"Log in":"Create account"}</button></form><button className="accountSwitch" onClick={()=>setMode(mode==="login"?"register":"login")}>{mode==="login"?"New here? Create a free account":"Already have an account? Log in"}</button><small>Free to use · no paid API required · local processing when supported</small></div></div>
}