import React,{useEffect,useState} from "react";
import {BrainCircuit,Cpu,Database,Download,ExternalLink,X,Zap} from "lucide-react";
import {DATASET_REGISTRY,MODEL_REGISTRY,datasetUrl,loadLocalLLM,recommendedModel,runtimeInfo} from "./aiModel.js";
import "./aiLab.css";

export function AILab({onClose,onModelReady}){
 const [model,setModel]=useState(recommendedModel().id),[status,setStatus]=useState("idle"),[progress,setProgress]=useState(0),[message,setMessage]=useState("ToollooT connects to the LLM running on your local PC.");
 useEffect(()=>{setModel(recommendedModel().id)},[]);
 const load=async()=>{setStatus("loading");setProgress(0);setMessage("Connecting to ASI-Core local PC…");try{const h=await loadLocalLLM(model,p=>setProgress(Math.max(0,Math.min(100,p?.progress||0))));setStatus(h.ready?"ready":"error");setProgress(h.ready?100:20);setMessage(h.ready?"SmolLM2 1.7B is live on the local PC.":"Local AI is offline. Start ASI-Core and retry.");onModelReady?.(model)}catch(e){setStatus("error");setMessage("Local AI server is unavailable.")}};
 return <div className="tlLabOverlay" role="dialog" aria-modal="true"><div className="tlLab"><header><div><span className="tlLabKicker"><BrainCircuit size={15}/>LOCAL AI LAB</span><h2>LLM + Neural Runtime</h2><p>Your browser is the UI; the 1.7B open model runs on the local PC.</p></div><button className="tlIconBtn" onClick={onClose}><X size={19}/></button></header>
 <section className="tlLabGrid"><div className="tlLabCard"><div className="tlLabCardHead"><Cpu size={18}/><b>Live LLM</b></div><select value={model} onChange={e=>{setModel(e.target.value);setStatus("idle")}}>{MODEL_REGISTRY.map(m=><option key={m.id} value={m.id}>{m.name} • {m.size}</option>)}</select><div className="tlModelMeta"><span>{runtimeInfo().mobile?"Mobile":"Desktop"} • {runtimeInfo().deviceLabel}</span><span>{runtimeInfo().cores} cores • Q4_K_M</span></div><button className="tlLabPrimary" onClick={load} disabled={status==="loading"}><Zap size={16}/>{status==="loading"?"Connecting…":status==="ready"?"AI online":"Check AI status"}</button>{status==="loading"&&<div className="tlProgress"><div style={{width:progress+"%"}}/></div>}<small className="tlLabNote">Inference stays on the PC. ToollooT does not download or run the 1.7B model in the browser.</small>{message&&<div className={"tlLabStatus "+status}>{message}</div>}</div>
 <div className="tlLabCard"><div className="tlLabCardHead"><Database size={18}/><b>Optional datasets</b></div><p className="tlLabIntro">Open datasets remain available for local experiments; the live assistant does not require them.</p>{DATASET_REGISTRY.map(d=><div className="tlDataset" key={d.id}><div><b>{d.name}</b><small>{d.size} • {d.license}</small></div><a href={datasetUrl(d.id,d.file)} download><Download size={15}/>Download</a><a href={"https://huggingface.co/datasets/"+d.id} target="_blank" rel="noreferrer" aria-label={"Open "+d.name}><ExternalLink size={14}/></a></div>)}</div></section>
 <footer><span>Inference: ASI-Core • SmolLM2 1.7B • local CPU</span><span>No browser LLM • no paid AI API</span></footer>
 </div></div>
}
