import React, { useEffect, useState } from "react";
import { BrainCircuit, Cpu, Database, Download, ExternalLink, X, Zap } from "lucide-react";
import { DATASET_REGISTRY, MODEL_REGISTRY, loadLocalLLM, modelUrl, recommendedModel, runtimeInfo } from "./aiModel.js";
import "./aiLab.css";

const size=(n)=>{const u=["B","KB","MB","GB"];let i=0;while(n>=1024&&i<3){n/=1024;i++}return `${n.toFixed(i?1:0)} ${u[i]}`};
export function AILab({onClose,onModelReady}){
 const [model,setModel]=useState(recommendedModel().id),[status,setStatus]=useState("idle"),[progress,setProgress]=useState(0),[message,setMessage]=useState("The fast model is prepared automatically in the background.");
 useEffect(()=>{setModel(recommendedModel().id)},[]);
 const load=async()=>{setStatus("loading");setProgress(0);setMessage("Preparing the local neural model…");try{await loadLocalLLM(model,p=>{const v=typeof p?.progress==="number"?p.progress:0;setProgress(Math.max(0,Math.min(100,v)))});setStatus("ready");setProgress(100);setMessage("LLM ready and cached on this device.");onModelReady?.(model)}catch(e){setStatus("error");setMessage("This browser/device could not run the selected model. ToollooT will retry with WASM when possible.")}};
 return <div className="tlLabOverlay" role="dialog" aria-modal="true"><div className="tlLab"><header><div><span className="tlLabKicker"><BrainCircuit size={15}/>LOCAL AI LAB</span><h2>LLM + Neural Runtime</h2><p>No manual model download is required. ToollooT prepares the fast local model automatically.</p></div><button className="tlIconBtn" onClick={onClose}><X size={19}/></button></header>
  <section className="tlLabGrid"><div className="tlLabCard"><div className="tlLabCardHead"><Cpu size={18}/><b>LLM models</b></div><select value={model} onChange={e=>{setModel(e.target.value);setStatus("idle");setMessage("Selected model is ready to prepare.")}}>{MODEL_REGISTRY.map(m=><option key={m.id} value={m.id}>{m.name} • {m.size}</option>)}</select><div className="tlModelMeta"><span>{runtimeInfo().mobile?"Mobile":"Desktop"} • {runtimeInfo().deviceLabel}</span><span>{runtimeInfo().cores} cores • q4</span></div><button className="tlLabPrimary" onClick={load} disabled={status==="loading"}><Zap size={16}/>{status==="loading"?"Preparing…":status==="ready"?"Model ready":"Prepare selected model"}</button>{status==="loading"&&<div className="tlProgress"><div style={{width:`${progress}%`}}/></div>}<small className="tlLabNote">Fast model: SmolLM2 135M. It is cached by the browser after preparation.</small>{message&&<div className={`tlLabStatus ${status}`}>{message}</div>}</div>
   <div className="tlLabCard"><div className="tlLabCardHead"><Database size={18}/><b>Training datasets</b></div><p className="tlLabIntro">Small open datasets for local experiments. Dataset downloads remain optional.</p>{DATASET_REGISTRY.map(d=><div className="tlDataset" key={d.id}><div><b>{d.name}</b><small>{d.size} • {d.license}</small></div><a href={modelUrl(d.id,d.file)} download><Download size={15}/>Download</a><a href={`https://huggingface.co/datasets/${d.id}`} target="_blank" rel="noreferrer" aria-label={`Open ${d.name}`}><ExternalLink size={14}/></a></div>)}</div></section>
  <footer><span>Neural inference: Transformers.js + ONNX</span><span>Local-first • browser cached</span></footer>
 </div></div>
}
