import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import{Sparkles,Search,Sun,Moon,Heart,Plus,ArrowRight,Image,FileText,Calculator,Shield,Settings,Menu,X}from"lucide-react";import"./chat.css";
const tools=[["Image Tools","Compress, resize, crop and convert images directly in your browser.",Image],["PDF Tools","Merge, split, compress and organize documents locally.",FileText],["Calculators","Useful everyday calculators and converters in one place.",Calculator],["Privacy Tools","Simple utilities designed around local processing and privacy.",Shield]];
function App(){const[dark,setDark]=useState(()=>localStorage.getItem("ioi:dark")==="1"),[q,setQ]=useState(""),[menu,setMenu]=useState(false),[ideas,setIdeas]=useState(()=>JSON.parse(localStorage.getItem("ioi:ideas")||"[]")),[idea,setIdea]=useState("");
useEffect(()=>{document.body.classList.toggle("dark",dark);localStorage.setItem("ioi:dark",dark)},[dark]);
const submit=e=>{e.preventDefault();if(!idea.trim())return;const x=[idea.trim(),...ideas].slice(0,20);setIdeas(x);localStorage.setItem("ioi:ideas",JSON.stringify(x));setIdea("")};
const filtered=tools.filter(x=>(x[0]+" "+x[1]).toLowerCase().includes(q.toLowerCase()));
return <div className="ioi"><header><button className="logo" onClick={()=>scrollTo({top:0,behavior:"smooth"})}><span>IOI</span></button><div className="tag">BY THE USER, FOR THE USER</div><nav className={menu?"open":""}><a href="#tools">Tools</a><a href="#ideas">Ideas</a><a href="#about">About</a><button onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button></nav><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
<main><section className="hero"><div className="eyebrow"><Sparkles/> Made for real users</div><h1>Useful things.<br/><em>Made together.</em></h1><p>IOI is a user-built space for simple, fast and privacy-friendly tools. No clutter. No forced accounts.</p><div className="heroActions"><a className="primary" href="#tools">Explore IOI <ArrowRight/></a><a className="secondary" href="#ideas">Suggest an idea</a></div></section>
<section id="tools" className="section"><div className="sectionHead"><div><small>START HERE</small><h2>Tools people actually need</h2></div><label><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Find a tool"/></label></div><div className="grid">{filtered.map(([n,d,I])=><article key={n}><div className="toolIcon"><I/></div><h3>{n}</h3><p>{d}</p><button>Open <ArrowRight/></button></article>)}</div></section>
<section id="ideas" className="ideas"><div><small>YOUR VOICE</small><h2>What should IOI build next?</h2><p>Tell us what you need. Ideas are saved in your browser on this device.</p></div><form onSubmit={submit}><textarea value={idea} onChange={e=>setIdea(e.target.value)} placeholder="I wish IOI could…"/><button className="primary"><Plus/> Add idea</button></form>{ideas.length>0&&<div className="ideaList">{ideas.slice(0,5).map((x,i)=><div key={i}><Heart/>{x}</div>)}</div>}</section>
<section id="about" className="about"><div className="bigLogo">IOI</div><div><small>THE PRINCIPLE</small><h2>By the user. For the user.</h2><p>IOI starts with a simple rule: technology should solve real problems without making users fight through unnecessary complexity.</p><div className="chips"><span>Free-first</span><span>Privacy-first</span><span>Open-source</span><span>Simple</span></div></div></section></main>
<footer><b>IOI</b><span>By the User, For the User.</span><button onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button><button><Settings/></button></footer></div>}
createRoot(document.getElementById("root")).render(<App/>);