import React,{useEffect,useRef,useState}from"react";
import{createRoot}from"react-dom/client";
import{Gamepad2,Trophy,LogIn,UserPlus,LogOut,Users,Copy,Play,Shield,RefreshCw}from"lucide-react";
import{io}from"socket.io-client";
import"./chat.css";
const API=import.meta.env.VITE_GAME_API||"http://localhost:3000",KEY="toolloot_arena_auth";
const save=x=>localStorage.setItem(KEY,JSON.stringify(x));const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||"null")}catch{return null}};
function Auth({onAuth}){const[m,setM]=useState("login"),[name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[err,setErr]=useState(""),[busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setBusy(true);setErr("");try{const r=await fetch(API+"/api/"+(m==="login"?"login":"register"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,email,password})}),d=await r.json();if(!r.ok)throw Error(d.error||"Request failed");save(d);onAuth(d)}catch(x){setErr(x.message)}finally{setBusy(false)}};return <div className="auth"><form className="authCard" onSubmit={submit}><div className="brand"><Gamepad2/> TOOLLOOT <b>ARENA</b></div><h1>{m==="login"?"Welcome back":"Create account"}</h1><p>Real-time multiplayer browser arena.</p>{m==="register"&&<input required placeholder="Player name" value={name} onChange={e=>setName(e.target.value)} maxLength={24}/>}<input required type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input required minLength="6" type="password" placeholder="Password (6+ characters)" value={password} onChange={e=>setPassword(e.target.value)}/>{err&&<div className="error">{err}</div>}<button className="primary" disabled={busy}>{m==="login"?<LogIn/>:<UserPlus/>}{busy?"Please wait...":m==="login"?"LOGIN":"REGISTER"}</button><button type="button" className="link" onClick={()=>setM(m==="login"?"register":"login")}>{m==="login"?"Create a new account":"Already have an account? Login"}</button></form></div>}
function Game({auth,onLogout}){const[tab,setTab]=useState("play"),[lb,setLb]=useState([]),[room,setRoom]=useState(""),[players,setPlayers]=useState([]),[connected,setConnected]=useState(false),[status,setStatus]=useState("Ready"),[socket,setSocket]=useState(null),[me,setMe]=useState(null),[code,setCode]=useState(""),canvas=useRef(null),drag=useRef(false),pos=useRef({x:500,y:330});
useEffect(()=>{fetch(API+"/api/leaderboard").then(r=>r.json()).then(setLb).catch(()=>{});fetch(API+"/api/me",{headers:{Authorization:"Bearer "+auth.token}}).then(r=>r.json()).then(setMe).catch(()=>{});const s=io(API,{auth:{token:auth.token}});setSocket(s);s.on("connect",()=>setConnected(true));s.on("disconnect",()=>setConnected(false));s.on("room:players",setPlayers);s.on("game:start",()=>setStatus("MATCH LIVE"));return()=>s.disconnect()},[auth.token]);
useEffect(()=>{const c=canvas.current,ctx=c.getContext("2d");let raf;const draw=()=>{const w=c.clientWidth,h=c.clientHeight,d=devicePixelRatio||1;if(c.width!==w*d||c.height!==h*d){c.width=w*d;c.height=h*d}ctx.setTransform(d,0,0,d,0,0);ctx.fillStyle="#090d18";ctx.fillRect(0,0,w,h);ctx.strokeStyle="#172139";for(let x=0;x<w;x+=50){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<h;y+=50){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}players.forEach(p=>{const x=p.x/1000*w,y=p.y/600*h;ctx.fillStyle=p.id===auth.user.id?"#8077ff":"#ff5570";ctx.beginPath();ctx.arc(x,y,14,0,7);ctx.fill();ctx.fillStyle="#fff";ctx.font="11px system-ui";ctx.textAlign="center";ctx.fillText(p.name.slice(0,12),x,y-20)});raf=requestAnimationFrame(draw)};raf=requestAnimationFrame(draw);return()=>cancelAnimationFrame(raf)},[players,auth.user.id]);
const move=e=>{if(!drag.current)return;const r=canvas.current.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*1000,y=(e.clientY-r.top)/r.height*600;pos.current={x,y};socket?.emit("player:move",{x,y})};
const join=x=>socket?.emit("room:join",x,d=>{if(d.error)setStatus(d.error);else{setRoom(d.code);setStatus("Lobby joined")}}),quick=()=>socket?.emit("room:quick",d=>{if(d.error)setStatus(d.error);else{setRoom(d.code);setStatus("Quick Match lobby")}}),create=()=>socket?.emit("room:create",d=>{setCode(d.code);join(d.code)});
return <div className="app"><header><div className="brand"><Gamepad2/> TOOLLOOT <b>ARENA</b></div><div className="headUser"><span>{auth.user.name}</span><button onClick={onLogout}><LogOut/></button></div></header><div className="nav"><button className={tab==="play"?"active":""} onClick={()=>setTab("play")}><Play/> PLAY</button><button className={tab==="leaderboard"?"active":""} onClick={()=>setTab("leaderboard")}><Trophy/> LEADERBOARD</button><span className={connected?"online":"offline"}>{connected?"● ONLINE":"● OFFLINE"}</span></div><main>{tab==="leaderboard"?<section className="panel"><h2><Trophy/> Global Leaderboard</h2><div className="table">{lb.map((p,i)=><div className="row" key={p.id}><b>#{i+1}</b><strong>{p.name}</strong><span>{p.wins} W</span><span>{p.kills} K</span><em>{p.score}</em></div>)}{!lb.length&&<p>No scores yet.</p>}</div></section>:<><section className="panel lobby"><div><h2><Shield/> Multiplayer Arena</h2><p>Signed in as <b>{auth.user.email}</b></p><div className="roomline"><input placeholder="ROOM CODE" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/><button onClick={()=>join(code)}>JOIN</button><button onClick={create}>CREATE</button><button onClick={quick}><RefreshCw/> QUICK</button></div>{room&&<div className="room"><b>ROOM {room}</b><button onClick={()=>navigator.clipboard?.writeText(room)}><Copy/> COPY</button></div>}<div className="status">{status}</div></div><div className="players"><Users/><b>{players.length}/10</b><small>PLAYERS</small></div></section><section className="arena"><canvas ref={canvas} onPointerDown={()=>drag.current=true} onPointerUp={()=>drag.current=false} onPointerLeave={()=>drag.current=false} onPointerMove={move}/><div className="hint">DRAG TO MOVE • CLICK SHOOT</div></section><section className="controls"><button className="primary" onClick={()=>socket?.emit("game:start",room)} disabled={!room}>START MATCH</button><button onClick={()=>socket?.emit("player:shoot",{x:pos.current.x,y:pos.current.y})}>SHOOT</button></section></>}</main><footer>ToollooT Arena • Real-time multiplayer • {me?"Score "+me.score:""}</footer></div>}
function App(){const[auth,setAuth]=useState(load());return auth?<Game auth={auth} onLogout={()=>{localStorage.removeItem(KEY);setAuth(null)}}/>:<Auth onAuth={setAuth}/>}createRoot(document.getElementById("root")).render(<App/>);