import {useEffect,useRef,useState} from "react";import*as THREE from"three";
const rnd=(a,b)=>a+Math.random()*(b-a);
function SpaceGame({onBack}){const ref=useRef(null),keys=useRef({}),[ui,setUi]=useState({score:0,distance:0,speed:32,high:+localStorage.getItem("star_runner_high")||0,over:false});
useEffect(()=>{const el=ref.current,s=new THREE.Scene();s.background=new THREE.Color(0x01030a);const c=new THREE.PerspectiveCamera(70,innerWidth/innerHeight,.1,1200),r=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"});r.setPixelRatio(Math.min(devicePixelRatio,1.5));r.setSize(innerWidth,innerHeight);el.appendChild(r.domElement);
s.add(new THREE.AmbientLight(0x6688aa,1.5));const sun=new THREE.DirectionalLight(0xffffff,2);sun.position.set(5,8,8);s.add(sun);
const sg=new THREE.BufferGeometry(),sp=new Float32Array(4500);for(let i=0;i<1500;i++){sp[i*3]=rnd(-180,180);sp[i*3+1]=rnd(-100,100);sp[i*3+2]=rnd(-900,80)}sg.setAttribute("position",new THREE.BufferAttribute(sp,3));s.add(new THREE.Points(sg,new THREE.PointsMaterial({color:0xffffff,size:.7})));
const ship=new THREE.Group(),body=new THREE.Mesh(new THREE.ConeGeometry(.65,2.5,6),new THREE.MeshStandardMaterial({color:0x42cfff,metalness:.7,roughness:.25}));body.rotation.x=-Math.PI/2;ship.add(body);const glass=new THREE.Mesh(new THREE.SphereGeometry(.3,10,8),new THREE.MeshStandardMaterial({color:0x9ef4ff,emissive:0x168cff,emissiveIntensity:.7}));glass.position.z=-.2;ship.add(glass);for(const x of[-.8,.8]){const w=new THREE.Mesh(new THREE.BoxGeometry(1.3,.12,.65),new THREE.MeshStandardMaterial({color:0x172c43,metalness:.8}));w.position.set(x*.7,0,.45);w.rotation.z=x<0?-.15:.15;ship.add(w)}ship.position.set(0,0,3);s.add(ship);
const objects=[];function spawn(){const kind=Math.random()<.72?"rock":"gate";let o;if(kind==="rock"){o=new THREE.Mesh(new THREE.IcosahedronGeometry(1,1),new THREE.MeshStandardMaterial({color:0x66717d,roughness:1}));o.scale.setScalar(rnd(1.1,2.8));}else{o=new THREE.Mesh(new THREE.TorusGeometry(rnd(3.5,5),.35,8,20),new THREE.MeshStandardMaterial({color:0x35d7ff,emissive:0x087a9c,emissiveIntensity:.45}));o.rotation.x=rnd(-.5,.5)}o.position.set(rnd(-11,11),rnd(-6,7),-170);o.userData={kind,passed:false};s.add(o);objects.push(o)}
const pickups=[];function coin(){const o=new THREE.Mesh(new THREE.TorusGeometry(.5,.16,8,16),new THREE.MeshStandardMaterial({color:0xffd34d,emissive:0xb56b00,emissiveIntensity:.5}));o.position.set(rnd(-11,11),rnd(-6,7),-170);s.add(o);pickups.push(o)}
for(let i=0;i<14;i++)spawn();for(let i=0;i<10;i++)coin();
let last=performance.now(),dist=0,score=0,speed=32,alive=true,spawnT=0,coinT=0,raf;
const kd=e=>{keys.current[e.key.toLowerCase()]=true;if(e.key==="r"&& !alive){alive=true;dist=0;score=0;speed=32;setUi(u=>({...u,over:false,score:0,distance:0,speed:32}));for(let i=0;i<objects.length;i++)objects[i].position.z=-30-i*12}};const ku=e=>keys.current[e.key.toLowerCase()]=false;addEventListener("keydown",kd);addEventListener("keyup",ku);
const resetObj=o=>{o.position.set(rnd(-11,11),rnd(-6,7),-170);o.userData.passed=false};const loop=t=>{const dt=Math.min(.035,(t-last)/1000);last=t;if(alive){const k=keys.current,dx=(k.d||k.arrowright?1:0)-(k.a||k.arrowleft?1:0),dy=(k.w||k.arrowup?1:0)-(k.s||k.arrowdown?1:0);ship.position.x=THREE.MathUtils.lerp(ship.position.x,THREE.MathUtils.clamp(ship.position.x+dx*18*dt,-12,12),.55);ship.position.y=THREE.MathUtils.lerp(ship.position.y,THREE.MathUtils.clamp(ship.position.y+dy*14*dt,-7,8),.55);ship.rotation.z=THREE.MathUtils.lerp(ship.rotation.z,-dx*.35,.12);speed=Math.min(75,speed+dt*.65);dist+=speed*dt;score=Math.floor(dist*2);
spawnT+=dt;coinT+=dt;if(spawnT>Math.max(.7,1.7-speed/70)){spawn();spawnT=0}if(coinT>1){coin();coinT=0}
objects.forEach(o=>{o.position.z+=speed*dt;o.rotation.x+=dt;o.rotation.y+=dt*.7;if(o.position.z>12)resetObj(o);if(o.position.distanceTo(ship.position)<2.1){alive=false;const h=Math.max(score,+localStorage.getItem("star_runner_high")||0);localStorage.setItem("star_runner_high",h);setUi(u=>({...u,score,distance:Math.floor(dist),speed:Math.floor(speed),high:h,over:true}))}});
pickups.forEach(o=>{o.position.z+=speed*dt;o.rotation.z+=dt*4;if(o.position.z>12)resetObj(o);if(o.position.distanceTo(ship.position)<1.5){score+=250;resetObj(o)}});
setUi(u=>({...u,score,distance:Math.floor(dist),speed:Math.floor(speed)}))}
c.position.lerp(new THREE.Vector3(ship.position.x*.35,ship.position.y*.3,ship.position.z+13),.08);c.lookAt(ship.position.x,ship.position.y,ship.position.z-35);r.render(s,c);raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);const rs=()=>{c.aspect=innerWidth/innerHeight;c.updateProjectionMatrix();r.setSize(innerWidth,innerHeight)};addEventListener("resize",rs);return()=>{cancelAnimationFrame(raf);removeEventListener("keydown",kd);removeEventListener("keyup",ku);removeEventListener("resize",rs);r.dispose();el.innerHTML=""}},[]);
return <div className="spaceGame"><div ref={ref} className="spaceCanvas"/><div className="runnerTop"><div><b>STAR RUNNER</b><span>INFINITE SPACE • DODGE • SURVIVE</span></div><button onClick={onBack}>EXIT</button></div><div className="runnerStats"><strong>{ui.score.toString().padStart(7,"0")}</strong><span>DISTANCE {ui.distance} m</span><span>SPEED {ui.speed}</span><span>BEST {ui.high}</span></div><div className="runnerHint">A D / ← → MOVE • W S / ↑ ↓ DODGE</div>{ui.over&&<div className="gameOver"><small>SHIP CRASHED</small><h1>GAME OVER</h1><p>SCORE {ui.score} • DISTANCE {ui.distance}m</p><button onClick={()=>location.reload()}>RUN AGAIN</button></div>}<div className="mobileRun"><button onPointerDown={()=>keys.current.a=true} onPointerUp={()=>keys.current.a=false}>◀</button><button onPointerDown={()=>keys.current.d=true} onPointerUp={()=>keys.current.d=false}>▶</button></div></div>}export default SpaceGame;