import * as THREE from "three";
import { GLTFLoader } from "https://cdn.jsdelivr.net/npm/three@0.186.1/examples/jsm/loaders/GLTFLoader.js";
const scene=new THREE.Scene();scene.background=new THREE.Color(0x08131b);scene.fog=new THREE.Fog(0x08131b,45,150);
const camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.1,300),renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;document.body.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xb9dcff,0x203020,2));const sun=new THREE.DirectionalLight(0xffffff,3);sun.position.set(30,50,20);sun.castShadow=true;scene.add(sun);
const assetRoot=new THREE.Group();scene.add(assetRoot);
const loader=new GLTFLoader();
const characterURL="https://cdn.3dassets.dev/assets/28265/v1/model.glb";
const characterLoader=new GLTFLoader();
characterLoader.load(characterURL,g=>{const model=g.scene;model.scale.setScalar(1.8);model.position.y=0;model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});window.realCharacter=model;},undefined,e=>console.warn("character asset failed",e));
loader.load("https://cdn.3dassets.dev/assets/28276/v1/model.glb",g=>{g.scene.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});assetRoot.add(g.scene)},undefined,e=>console.warn("Battle assets failed",e));
const lootLoader=new GLTFLoader();
lootLoader.load("https://cdn.3dassets.dev/assets/28220/v1/model.glb",g=>{const rifle=g.scene;rifle.scale.setScalar(1.4);rifle.position.set(8,.15,3);rifle.rotation.y=.7;rifle.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});scene.add(rifle)},undefined,e=>console.warn("Loot asset failed",e));
const zone=new THREE.Mesh(new THREE.CylinderGeometry(48,48,.08,96),new THREE.MeshBasicMaterial({color:0x39a9ff,transparent:true,opacity:.09}));zone.position.y=.05;scene.add(zone);const ring=new THREE.Mesh(new THREE.RingGeometry(47.7,48,96),new THREE.MeshBasicMaterial({color:0x55c8ff,transparent:true,opacity:.8,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=.08;scene.add(ring);
let me={id:"local_"+Math.random().toString(36).slice(2,8),name:"Player",x:0,y:0,rot:0,alive:true},players=new Map(),keys={},yaw=0,pitch=.25,lastShot=0;const id=me.id,name="Player-"+id.slice(6); players.set(id,{mesh:makePlayer(me,true),data:me}); document.querySelector("#count").textContent="1";
const ws=new WebSocket(location.protocol==="file:"||location.hostname==="localhost"?"ws://localhost:5190":(location.protocol==="https:"?"wss://"+location.host:"ws://"+location.host));
function makePlayer(p,self){const g=new THREE.Group();if(window.realCharacter){g.add(window.realCharacter.clone(true))}else{const body=new THREE.Mesh(new THREE.CapsuleGeometry(.55,1.15,5,10),new THREE.MeshStandardMaterial({color:self?0x33aaff:0xff4d5d}));body.position.y=1.15;g.add(body)}scene.add(g);g.position.set(p.x,0,p.y);return g}
function sync(p){let o=players.get(p.id);if(!o){o={mesh:makePlayer(p,p.id===id),data:p};players.set(p.id,o)}o.data=p;o.mesh.position.x=p.x;o.mesh.position.z=p.y;o.mesh.rotation.y=p.rot||0;o.mesh.visible=p.alive!==false}
function send(type,data={}){if(ws.readyState===1)ws.send(JSON.stringify({type,...data}))}
ws.onopen=()=>{document.querySelector("#status").textContent="ONLINE";send("join",{id,name})};ws.onclose=()=>document.querySelector("#status").textContent="OFFLINE";ws.onerror=()=>document.querySelector("#status").textContent="SERVER ERROR";
ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==="state"){m.players.forEach(sync);me=m.players.find(p=>p.id===id)||me}else if(m.type==="player_join"){sync(m.player)}else if(m.type==="move"){sync(m.player)}else if(m.type==="player_leave"){const o=players.get(m.id);if(o){scene.remove(o.mesh);players.delete(m.id)}}else if(m.type==="hit"&&m.target===id)document.querySelector("#hp").textContent=m.hp;document.querySelector("#count").textContent=players.size};
addEventListener("keydown",e=>keys[e.code]=true);addEventListener("keyup",e=>keys[e.code]=false);
let drag=false,lastX=0,lastY=0;addEventListener("pointerdown",e=>{if(e.target.id==="fire")return;drag=true;lastX=e.clientX;lastY=e.clientY});addEventListener("pointerup",()=>drag=false);addEventListener("pointermove",e=>{if(!drag)return;yaw-=(e.clientX-lastX)*.006;pitch=THREE.MathUtils.clamp(pitch-(e.clientY-lastY)*.004,-.15,.75);lastX=e.clientX;lastY=e.clientY});
function shoot(){if(performance.now()-lastShot<350)return;lastShot=performance.now();send("shoot",{x:me?.x||0,y:me?.y||0,rot:yaw})}addEventListener("pointerdown",e=>{if(e.target.id!=="fire")shoot()});document.querySelector("#fire").addEventListener("pointerdown",e=>{e.preventDefault();shoot()});
function loop(){requestAnimationFrame(loop);if(me){let dx=0,dz=0;if(keys.KeyW||keys.ArrowUp)dz-=1;if(keys.KeyS||keys.ArrowDown)dz+=1;if(keys.KeyA||keys.ArrowLeft)dx-=1;if(keys.KeyD||keys.ArrowRight)dx+=1;const l=Math.hypot(dx,dz)||1;dx/=l;dz/=l;const speed=.14,c=Math.cos(yaw),s=Math.sin(yaw);me.x=THREE.MathUtils.clamp(me.x+(dx*c-dz*s)*speed,-66,66);me.y=THREE.MathUtils.clamp(me.y+(dx*s+dz*c)*speed,-66,66);me.rot=yaw;const o=players.get(id);if(o){o.mesh.position.set(me.x,0,me.y);o.mesh.rotation.y=yaw}send("move",{x:me.x,y:me.y,rot:yaw})}if(me){camera.position.lerp(new THREE.Vector3(me.x+Math.sin(yaw)*7,4.3,me.y+Math.cos(yaw)*7),.12);camera.lookAt(new THREE.Vector3(me.x,1.4,me.y))}renderer.render(scene,camera)}loop();addEventListener("resize",()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});